# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{haruharu}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shota Fukumori (sora_h)"]
  s.date = %q{2011-04-26}
  s.description = %q{about streaming receiver. streaming server is not included.}
  s.email = %q{sorah@tubusu.net}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
    "RakeFile",
    "VERSION",
    "lib/haruharu.rb",
    "test_eew.rb"
  ]
  s.homepage = %q{http://github.com/sorah/haruharu}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{about streaming receiver}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

